### ISSUE TITLE
chopping a ZIP file into fragments

### ISSUE THREAD

**Issue by BradKML** [DavidBuchanan314/tweetable-polyglot-png#3]
Since ZIP allow data splitting, take a look at https://kb.winzip.com/help/winzip/help_splitdlg.htm
Imagine a tweet thread with split files

**Comment by DavidBuchanan314** [comment]
This project should already work with split zip files.

**Comment by BradKML** [comment]
Clarification on https://github.com/DavidBuchanan314/tweetable-polyglot-png#embedded-file-requirements 
Sinde it does not hint at the use of the split function when creating the image, maybe I read that wrong.

**Comment by DavidBuchanan314** [comment]
Are you suggesting an update to the readme? How would you phrase it differently?

**Comment by BradKML** [comment]
"If the embedded file is a .zip, then the offsets are automatically adjusted so that the overall file is still a valid zip."
This can be interpreted as a partial file, which does not quite make sense. Maybe:
"If the embedded file is a .zip, then it will be divided into partial zip files, each stored in a separate image."

**Comment by DavidBuchanan314** [comment]
Oh, that's not the current behavior. Zipping files is out-of-scope of this project, it just packs pre-zipped files. How those files are zipped is entirely up to the end-user.

**Comment by dardysing69** [comment]
I like this feature

Sent from my iPhone

On 22 Mar 2021, at 1:44 pm, BrandonKMLee ***@***.***> wrote:

﻿

"If the embedded file is a .zip, then the offsets are automatically adjusted so that the overall file is still a valid zip."
This can be interpreted as a partial file, which does not quite make sense. Maybe:
"If the embedded file is a .zip, then it will be divided into partial zip files, each stored in a separate image."

**Comment by dardysing69** [comment]
Is bit torrent any good ??

Sent from my iPhone

On 22 Mar 2021, at 2:29 pm, luke graham ***@***.***> wrote:

﻿ I like this feature

Sent from my iPhone

On 22 Mar 2021, at 1:44 pm, BrandonKMLee ***@***.***> wrote:

﻿

"If the embedded file is a .zip, then the offsets are automatically adjusted so that the overall file is still a valid zip."
This can be interpreted as a partial file, which does not quite make sense. Maybe:
"If the embedded file is a .zip, then it will be divided into partial zip files, each stored in a separate image."
